apiVersion: v1
kind: ConfigMap
metadata:
  name: php-code
data:
  index.php: |
    <?php
    $host = 'mysql';
    $user = 'root';
    $pass = getenv('MYSQL_ROOT_PASSWORD');
    $conn = new mysqli($host, $user, $pass);

    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    }
    echo "Hello World from PHP! Connected to MySQL successfully.";
    ?>