apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - image: php-mysqli:latest
        name: php
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 9000
          name: php
        volumeMounts:
        - name: fileadmin
          mountPath: /var/www/html/public/fileadmin
      volumes:
      - name: fileadmin
        persistentVolumeClaim:
          claimName: fileadmin-pvc